language: cpp
dist: trusty
sudo: required
group: edge

compiler:
  - gcc
matrix:
  include:
    # build on ubuntu
    - os: linux
      compiler: gcc
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
    # build on osx
    - os: osx
      osx_image: xcode9.4

    - os: osx
      osx_image: xcode10.3

    - os: osx
      osx_image: xcode11

before_install:
    - eval "${MATRIX_EVAL}"
script:
  - mkdir build
  - cd build
  - cmake .. && make
