codecov:
  branch: master
  ci:
    # Don't wait for AppVeyor build to finalize coverage information
    # We don't have a way to generate coverage from it anyway
    - !appveyor

coverage:
  ignore:
    - "projects/SelfTest"
    - "**/catch_reporter_tap.hpp"
    - "**/catch_reporter_automake.hpp"
    - "**/catch_reporter_teamcity.hpp"
    - "**/external/clara.hpp"
